config_diff_export.export_form:
  title: 'Configuration Diff Export'
  route_name: config_diff_export.export_form
  description: 'Export configuration diff as packed archive'
  parent: system.admin_config_development
  weight: 99

