export config diff:
  title: 'Export Configuration Diff'
  description: 'Export configuration diff as archive file.'
  warning: 'Warning: Give to trusted roles only; this permission has security implications.'
  restrict access: TRUE